### PR TITLE
Newsweek full page

### PR DESCRIPTION
**Pull request by c-m-a**

### CODE REVIEW

**Comment by pelzolga123** [comment]
## Hi Cmauricio!  
#### Your project looks :+1: amazing!
* [x] **Please check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project and they need to be fixed.

* [x] **Footer needs to be fixed, icons should be under logo**
image

Original: 
 image


Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*Happy coding *

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Validator errors need to be fixed and footer requires some responsivity changes.

**Comment by c-m-a** [comment]
### Hi Olga! 

Thank you very much for your feeback! :)

**Review by MauricioRobayo — APPROVED** [review]
Congrats! Everything seems as it is supposed to be. You did a great job!

This is **approved**. Go ahead and merge, and keep up the good work!

**Review by MauricioRobayo — APPROVED** [review]

**Pull request merged**
